// src/core/ipcChannels.js
// Canonical IPC channel names to avoid typos.
module.exports = {
  PERSIST_WINDOW_STATE: 'persist-window-state',
  PICK_IMAGE_FILE: 'pick-image-file',
  TWITCH_CONNECT: 'twitch-connect',
  TWITCH_OAUTH_FLOW: 'twitch-oauth-flow',
  TWITCH_OAUTH_TOKEN: 'twitch-oauth-token',
  TWITCH_SEND_CHAT: 'twitch-send-chat',
  TWITCH_FORGET_CREDS: 'twitch-forget-chat-creds',
  TWITCH_CHAT_STATUS: 'twitch-chat-status',
  TWITCH_CHAT: 'twitch-chat',
  TWITCH_REDEEM: 'twitch-redeem',
  TWITCH_POINTS: 'twitch-points',
  TWITCH_BITS: 'twitch-bits',
  TWITCH_TRIGGER: 'twitch-trigger',
  TWITCH_PUBSUB_STATUS: 'twitch-pubsub-status',
  TWITCH_AVATAR_CHANGE: 'twitch-avatar-change',
  TWITCH_DEBUG_LOG: 'twitch-debug-log',
  TWITCH_GET_DEBUG_LOG: 'twitch-get-debug-log',
  TWITCH_CLEAR_DEBUG_LOG: 'twitch-clear-debug-log',
  TWITCH_HEALTH: 'twitch-health',
  // YouTube channels
  YOUTUBE_CONNECT: 'youtube-connect',
  YOUTUBE_DISCONNECT: 'youtube-disconnect',
  YOUTUBE_STATUS: 'youtube-status',
  YOUTUBE_HEALTH: 'youtube-health',
  YOUTUBE_VALIDATE_KEY: 'youtube-validate-key',
  YOUTUBE_GET_CHANNEL_INFO: 'youtube-get-channel-info',
  YOUTUBE_AVATAR_CHANGE: 'youtube-avatar-change',
  // Discord channels
  DISCORD_CONNECT: 'discord-connect',
  DISCORD_DISCONNECT: 'discord-disconnect',
  DISCORD_STATUS: 'discord-status',
  DISCORD_HEALTH: 'discord-health',
  DISCORD_VALIDATE_TOKEN: 'discord-validate-token',
  DISCORD_GET_CHANNEL_INFO: 'discord-get-channel-info',
  DISCORD_SEND_MESSAGE: 'discord-send-message',
  GET_EXTENSION_SETTINGS: 'get-extension-settings',
  LOAD_SETTINGS: 'load-settings',
  SAVE_SETTINGS: 'save-settings',
  GET_ASSETS_LIST: 'get-assets-list',
  GET_BOSS_MANIFEST: 'get-boss-manifest',
  ASSETS_UPDATED: 'assets-updated',
  BOSS_MANIFEST: 'boss-manifest'
};
